name: ğŸš€ Publicar LeilÃµes Reversa

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ğŸ‰ Deploy para Hostinger
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Baixando CÃ³digo
      uses: actions/checkout@v4

    - name: ğŸŸ¢ Configurando Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: ğŸ“¦ Instalando DependÃªncias
      run: npm install

    - name: ğŸ”¨ Construindo Site (Build)
      run: npm run build
      env:
        API_KEY: ${{ secrets.API_KEY }} 

    - name: ğŸ“‚ Sincronizando via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: public_html/
        delete-remote: true
